// languageContext.js
import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("en");

  const translations = {
    en: {
        indexTitle: "Welcome to bmCode, let's get to know each other",
        nameHolder: 'How can I call you?',
        researchTitle: "what would you like to learn?",
        home: "Home",
        dashboard: "Dashboard",
        settings: "Settings",
        reviewAll: "Review all",
        reviewNeeded: "Review needed",
        submit: "Submit",
        letsgo: "Let's go",
        chooseCardNumber: "Choose the number of cards in a round:",
        showOnlyFavorite: "Only favorites",
        sortBy: "Sort by:",
        diffAsc: "Difficulty level – easy first",
        diffDesc: "Difficulty level – hard first",
        dateAsc: "Last reviewed date – recent first",
        dateDesc: "Last reviewed date – oldest first",
        name: "Name",
        version: "Version",
        feedback: "Feedback",
        about: "About",
        organization: "Organization",
        language: 'Language',
        english: "English",
        russian: "Russian",
        turkmen: "Turkmen",
        founder: "Founder, author",
        location: "Location",
        totalReviewed: "repetitions",
        feedbackTitle: "we'd love to hear from you!",
        yourFavoriteTopics: "Your favorite topics",
        yourFavoriteCards: "Your favorite cards",
        mostReviewedCards: "Most reviewed cards",
        show: 'Show',
        back: "Back",
        quit: "Quit",
        next: "Next",
        finish: "Finish",
        fullName: "Full name",
        email: "Email",
        feedbackHolder: "What's on your mind?",
        noFavs: "You don't have favorite cards yet",
        reviewedCards: "Reviewed cards",
        remaining: "Remaining",
        results: "Results",
        continue: 'Continue',
        chooseLanguage: "Choose language： ",
        error1: 'Please, fill out all the fields',
        error2: 'The feedback must include at least 20 characters',
        error3: 'The feedback must include less than 800 characters',
        error4: 'Please, enter a valid email',
        error5: "The name must include at leats 3 characters!",
        error6: "Choose at least one topic",
        sthWrong: 'Oops, something went wrong. Please, check your internet connection',
        secretText: "Dedicated to my lovely sister Gulshat and my wonderful parents, I love you all"
    },
    ru: {
        indexTitle: "Добро пожаловать в bmCode, давайте познакомимся",
        nameHolder: "Как вас зовут?",
        researchTitle: "что бы вы хотели изучить?",
        home: "Главная",
        dashboard: "Статистика",
        settings: "Настройки",
        reviewAll: "Повторить все",
        reviewNeeded: "Повторить забытые",
        submit: "Отправить",
        letsgo: "Вперед",
        close: "Закрыть",
        chooseCardNumber: "Выберите число карточек в раунде:",
        showOnlyFavorite: "Только избранные",
        sortBy: "Упорядочить по:",
        diffAsc: "Уровню сложности – сначала легкие",
        diffDesc: "Уровню сложности – сначала сложные",
        dateAsc: "Дате последнего повтора – сначала недавние",
        dateDesc: "Дате последнего повтора – сначала давние",
        name: "Имя",
        version: "Версия",
        feedback: "Обратная связь",
        about: "О нас",
        organization: "Организация",
        language: "Язык",
        english: "Английский",
        russian: "Русский",
        turkmen: "Туркменский",
        founder: "Основатель, автор",
        location: "Местоположение",
        totalReviewed: "просмотров",
        feedbackTitle: "мы будем рады услышать ваше мнение!",
        yourFavoriteTopics: "Избранные темы",
        yourFavoriteCards: "Избранные карточки",
        mostReviewedCards: "Самые повторяемые карточки",
        show: 'Показать',
        back: "Назад",
        quit: "Выйти",
        next: "Следующий",
        finish: "Закончить",
        fullName: "Полное имя",
        email: "Электронная почта",
        feedbackHolder: "Ваши мысли?",
        noFavs: "У вас нет избранных карточек",
        reviewedCards: "Повторено",
        remaining: "Осталось",
        results: "Результаты",
        continue: 'Продолжить',
        chooseLanguage: "Выберите язык： ",
        error1: 'Пожалуйста, заполните все поля',
        error2: 'Текст должен состоять из минимум 20 символов',
        error3: 'Текст не может иметь более 800 символов',
        error4: 'Пожалуйста, предоставьте правильный адрес почты',
        error5: "Имя должно иметь минимум 3 символа!",
        error6: "Выберите как минимум одну подкатегорию",
        sthWrong: 'Что-то пошло не так. Пожалуйста, проверьте соединение',
        secretText: "Посвящается моей любимой сестре Гульшат и моим замечательным родителям, я люблю вас",
    },
    tkm: {
        indexTitle: "bmCode\nhoş geldiňiz!\n",
        nameHolder: "Size nähili ýüzlenip bileris?",
        researchTitle: "siz näme owrenmek isleýärsiňiz?",
        home: "Baş sahypa",
        dashboard: "Statistika",
        settings: "Sazlamalar",
        reviewAll: "Ählini gaýtalamak",
        reviewNeeded: "Zerurlary gaýtalamak",
        submit: "Ugrat",
        letsgo: "Başla",
        close: "Ýygna",
        chooseCardNumber: "Bir tapgyrda kartlaryň sany:",
        showOnlyFavorite: "Diňe saýlananlar",
        sortBy: "Tertip:",
        diffAsc: "Kynlygy boýunça – ilki aňsatlar",
        diffDesc: "Kynlygy boýunça – ilki kynlar",
        dateAsc: "Senesi boýunça – ilki ýakynda görülen",
        dateDesc: "Senesi boýunça – ilki öň görülen",
        name: "Adyňyz",
        version: "Wersiýa",
        feedback: "Habarlaşmak",
        about: "Biz barada",
        organization: "Gurama",
        language: "Dil",
        english: "Iňlisçe",
        russian: "Rusça",
        turkmen: "Türkmençe",
        founder: "Esaslandyryjy, awtor",
        location: "Ýerleşýän ýeri",
        totalReviewed: "gaýtalamalar",
        feedbackTitle: "siziň pikirleriňizi eşitmäge şat bolarys!",
        yourFavoriteTopics: "Saýlanan temalar",
        yourFavoriteCards: "Saýlanan kartlar",
        mostReviewedCards: "Iň köp gaýtalanýan kartlar",
        show: 'Görkez',
        back: "Yza",
        quit: "Çykmak",
        next: "Indiki",
        finish: "Tamamlama",
        fullName: "Doly adyňyz",
        email: "Elektron poçtaňyz",
        feedbackHolder: "Pikirleriňiz?",
        noFavs: "Sizde saýlanan kart ýok",
        reviewedCards: "Gaýtalanan",
        remaining: "Galdy",
        results: "Netijeler",
        continue: 'Dowam et',
        chooseLanguage: "Dil saýlaň： ",
        error1: 'Ähli maglumatlary dolduryň',
        error2: 'Tekst 20 simwoldan az bolmaly däl',
        error3: 'Tekst 800 simwoldan köp bolmaly däl',
        error4: 'Dogyr elektron poçta adresy ýazyň',
        error5: "Adyňyz iň azyndan 3 harpdan ybarat bolmaly!",
        error6: "Iň azyndan 1 podtema saýlaň",
        sthWrong: 'Näsazlyk döredi. Internet aragatnaşygy barlamagy haýyş edýäris',
        secretText: "Doganym Gülşada we ene-atama bagyşlanýar",        
    }
}

  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ t, setLanguage, language }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);